// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDve4ifJeHOwt2I7fJ1pA4QaUiY_6D4jpw',
    appId: '1:357307456100:web:1aa0605942fd2721c25d71',
    messagingSenderId: '357307456100',
    projectId: 'raiyan-cw03',
    authDomain: 'raiyan-cw03.firebaseapp.com',
    storageBucket: 'raiyan-cw03.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWxEHUtLOLnA6MHEU2xAAoW9Q7Kxw0hbU',
    appId: '1:357307456100:android:625faa70d061ded0c25d71',
    messagingSenderId: '357307456100',
    projectId: 'raiyan-cw03',
    storageBucket: 'raiyan-cw03.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaKXUaUrnQFVF4ehuGvWvmvHZzIzTmD6s',
    appId: '1:357307456100:ios:e7f4b366fc8dd970c25d71',
    messagingSenderId: '357307456100',
    projectId: 'raiyan-cw03',
    storageBucket: 'raiyan-cw03.firebasestorage.app',
    iosBundleId: 'com.example.cw03',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaKXUaUrnQFVF4ehuGvWvmvHZzIzTmD6s',
    appId: '1:357307456100:ios:e7f4b366fc8dd970c25d71',
    messagingSenderId: '357307456100',
    projectId: 'raiyan-cw03',
    storageBucket: 'raiyan-cw03.firebasestorage.app',
    iosBundleId: 'com.example.cw03',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDve4ifJeHOwt2I7fJ1pA4QaUiY_6D4jpw',
    appId: '1:357307456100:web:c417adc5dcc6e0efc25d71',
    messagingSenderId: '357307456100',
    projectId: 'raiyan-cw03',
    authDomain: 'raiyan-cw03.firebaseapp.com',
    storageBucket: 'raiyan-cw03.firebasestorage.app',
  );
}
